defaults:
  - _self_
  - dataset: arc_agi_2 # Which dataset to use
  - environment: arcle_env # Which environment to use

paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  data_interim: "data/interim"
  data_external: "data/external"
